-- GA4 por dispositivo (deviceCategory), diario.
-- Puebla el sync scripts/sync_ga4_to_supabase.py (bloque protegido "GA4 por dispositivo").
-- Ejecutar UNA vez en el editor SQL de Supabase.

create table if not exists public.ga4_device_daily (
  id                  bigint generated by default as identity primary key,
  date_str            text not null,
  year                int,
  month               int,
  day                 int,
  device              text not null,               -- desktop, mobile, tablet
  sessions            numeric,
  item_views          numeric,
  add_to_carts        numeric,
  checkouts           numeric,
  ecommerce_purchases numeric,
  purchase_revenue    numeric,
  created_at          timestamptz default now(),
  updated_at          timestamptz default now(),
  unique (date_str, device)
);

alter table public.ga4_device_daily enable row level security;

drop policy if exists "public read ga4_device_daily" on public.ga4_device_daily;
create policy "public read ga4_device_daily"
  on public.ga4_device_daily for select using (true);
