-- cohort_retention — matriz de cohortes para el LTV real (Sprint 3).
-- Una fila por (cohorte de adquisición) × (mes de vida). La cohorte es el mes de la
-- PRIMERA compra del cliente; life_month = meses transcurridos desde esa primera compra
-- (0 = mes de adquisición). Poblada por sync_connectif_to_supabase.py a partir del
-- informe Data Explorer "V. Cohortes" (ver CLAUDE.md §16).
--
-- Métricas por celda:
--   buyers      = compradores de la cohorte activos (que compran) ese mes de vida
--   revenue     = revenue de la cohorte ese mes de vida
--   cohort_size = tamaño inicial de la cohorte (buyers en life_month = 0); redundante
--                 por fila para simplificar la lectura en el frontend.

create table if not exists public.cohort_retention (
  id           bigint generated by default as identity primary key,
  cohort_year  int  not null,
  cohort_month int  not null,
  life_month   int  not null,          -- 0,1,2,... meses desde la primera compra
  buyers       int  not null default 0,
  revenue      numeric not null default 0,
  cohort_size  int  not null default 0,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  unique (cohort_year, cohort_month, life_month)
);

alter table public.cohort_retention enable row level security;

-- Lectura pública (dashboard interno, mismo patrón que el resto de tablas).
drop policy if exists "cohort_retention_read" on public.cohort_retention;
create policy "cohort_retention_read" on public.cohort_retention for select using (true);

create index if not exists cohort_retention_cohort_idx
  on public.cohort_retention (cohort_year, cohort_month);
